erDiagram
   e["Exam"] {
    int exam_id PK 
    year acad_year
    varchar exam_type "we need to manage end/mid thing"
    int semester
    varchar course_code FK 
    date day_of_exam
    int No_Of_Rooms
    int No_Of_Invigilators
    int No_Of_Students
    int No_Of_Relievers
    int No_Of_Squads
    int Dept_Id FK
    Date Creation_Date
    varchar Created_By
    }

    d["Department"] {
        int Dept_Id PK
        varchar Dept_Name
    }


    c["Course"] {
        varchar course_code PK
        varchar course_name
        int semester
    }

    es["Exam Slot"] {
        int Slot_Id PK
        int exam_id FK,PK
        int staff_id
        varchar duty_type 
    }

    s["Staff"] {
        int staff_id PK
        int employee_id 
        varchar staff_type 
        varchar grade FK
        varchar first_name
        varchar last_name
        int mobile_number
        varchar email
        varchar location
    }

    sd["Staff Duties"] {
        int staff_duty_id PK
        int staff_id FK
        year acad_year FK
        varchar exam_type FK
        int duty_count
    }

    r["Role"] {
        int role_id PK
        varchar role_name
    }

    g["Grade"] {
        varchar grade PK 
        int grade_duties
    }

    e ||--|{ es : alloted
    e }|..|| d : belongs
    c ||..|{ e : has_exam
    e }|..|{ sd : of_exam 
    es }|..|| sd : assigned
    s ||..o{ sd : duties
    c }o..|{ s : teaches
    s }|..o| g : grade_info
    r }|..|{ s : staff_role